name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
  check-workspace:
    name: Build, lint, and test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        id: toolchain
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Cache workspace
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ steps.toolchain.outputs.cachekey }}
      - name: Check formatting
        run: |
          cargo fmt --check
      - name: Lint
        run: cargo clippy --all-targets -- -D warnings
      - name: Lint with commercial feature flag
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Test
        shell: bash
        run: |
          cargo test
      - name: Test with commercial feature flag
        shell: bash
        run: |
          cargo test --all-features
